# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: philippe.virouleau@imag.fr
description: > # this means to ignore newlines until "baseurl:"
  Webpage of Philippe Virouleau.
  Posts about computer science, Rubik's cube, and random stuff.
url: "http://www.philippevirouleau.com"
title: ~Philippe Virouleau

baseurl: ''

github_username: 'viroulep'

excerpt_separator: <!--more-->


#paginate: 3

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', 'Session.vim']
